#!/usr/bin/expect -f

spawn ./test.sh

expect "Enter the key/name that will serve to identify the dotCMS instance (must be unique) "
send "demo\n"

expect "Enter the dotCMS base URL (must be a valid URL starting protocol http or https) "
send "https://demo.dotcms.com\n"

expect "Are these values OK? (Enter to confirm or N to cancel)  (Y/n)"
send "y\n"

expect "Do you want to continue adding another dotCMS instance?  (Y/n)"
send "n\n"

wait
