name: Checkout
on:
  push:

jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: ls -la
      - uses: actions/checkout@v4
      - name: List Files After Checkout
        run: ls -la  
        