name: PR Event
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  after-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get PR Labels'
        id: get_pr_labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: |
          echo "::group::Get PR Labels"
          echo "PR Labels: $LABELS"
          # Comprobar si alguna de las etiquetas es "sdk-libs"
          if echo "$LABELS" | jq -e '.[] | select(.name == "sdk-libs")' > /dev/null; then
            echo "La etiqueta 'sdk-libs' existe."
            PUBLISH=true
          else
            echo "La etiqueta 'sdk-libs' no existe."            
            PUBLISH=false
          fi
          echo "publish-sdk-libs=$PUBLISH" >> $GITHUB_OUTPUT
          echo "::endgroup::"          

      - name: 'Publish SDK Libraries'
        if: steps.get_pr_labels.outputs.publish-sdk-libs == 'true'
        run: |
          echo "::group::Publish SDK Libraries"
          echo "Publishing SDK Libraries in the NPM Registry..."
          echo "::endgroup::"
