name: PR Event
on:
  pull_request:
    # types: [opened, assigned, synchronize, reopened]

jobs:
  after-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Log GitHub context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "::group::Github Context"
          echo "$GITHUB_CONTEXT"
          echo "::endgroup::"          


# name: 'PR closed'
# on:
#   pull_request:

# jobs:
#   after-pr:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Log GitHub context'
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: |
#           echo "::group::Github Context"
#           echo "$GITHUB_CONTEXT"
#           echo "::endgroup::"
          
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.pull_request.head.ref }}
#           token: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Get PR Labels
      #   id: get_pr_labels
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const prNumber = context.payload.pull_request.number;
      #       const { data: labels } = await github.issues.listLabelsOnIssue({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: prNumber
      #       });
      #       return {
      #         labels: labels.map(label => label.name)
      #       }

      # - name: Evaluate PR Labels
      #   id: evaluate_pr_labels
      #   run: |
      #     LABELS=${{ steps.get_pr_labels.outputs.labels }}
      #     echo "PR Labels: $LABELS"
      #     if [[ "$LABELS" == *"sdk libs"* ]]; then
      #       echo "Specific label found. Proceeding with publishing."
      #       echo "publish=true" >> $GITHUB_ENV
      #     else
      #       echo "Specific label not found. Exiting."
      #       echo "publish=false" >> $GITHUB_ENV            
