name: PR Event
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  after-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Log GitHub context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "::group::Github Context"
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_CONTEXT" | jq ".event.pull_request"
          echo "::endgroup::"          

      # - name: Get PR Labels
      #   id: get_pr_labels
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const { owner, repo } = context.repo;
      #       const pull_number = context.payload.pull_request.number;
  
      #       const { data: pullRequest } = await github.pulls.get({
      #         owner: owner,
      #         repo: repo,
      #         pull_number: pull_number,
      #       });
  
      #       console.log(pullRequest);

      # - name: Evaluate PR Labels
      #   id: evaluate_pr_labels
      #   run: |
      #     LABELS=${{ steps.get_pr_labels.outputs.labels }}
      #     echo "PR Labels: $LABELS"
      #     if [[ "$LABELS" == *"sdk-libs"* ]]; then
      #       echo "Specific label found. Proceeding with publishing."
      #       echo "publish=true" >> $GITHUB_ENV
      #     else
      #       echo "Specific label not found. Exiting."
      #       echo "publish=false" >> $GITHUB_ENV            
