name: PR Event
on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  SDK_LABEL: 'sdk-libs'

jobs:
  after-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get PR Labels'
        id: get_pr_labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: |
          echo "::group::Get PR Labels"
          echo "PR Labels: $LABELS"

          if echo "$LABELS" | jq -e '.[] | select(.name == "${{ env.SDK_LABEL }}")' > /dev/null; then
            echo "Label '${{ env.SDK_LABEL }}' is present."
            PUBLISH=true
          else
            echo "Label '${{ env.SDK_LABEL }}' is not present."            
            PUBLISH=false
          fi
          echo "publish-sdk-libs=$PUBLISH" >> $GITHUB_OUTPUT
          echo "::endgroup::"          

      - name: 'Publish SDK Libraries'
        if: steps.get_pr_labels.outputs.publish-sdk-libs == 'true'
        run: |
          echo "::group::Publish SDK Libraries"
          echo "Publishing SDK Libraries in the NPM Registry..."
          echo "::endgroup::"
