name: Docker
on: [workflow_dispatch]
jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        FOO: bar
    steps:
      - name: Log Node & OS versions
        run: |
          node -v
          cat /etc/*-release

      - name: Log environment variables
        run: echo "FOO=$FOO"

      - name: Create a file
        run: echo "My text" > text.txt

      - name: Container in a step
        uses: docker://node:18.20-alpine3.20
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3

      - name: Showing the file content
        uses: docker://node:18.20-alpine3.20
        with:
          entrypoint: cat
          args: text.txt

      - uses: actions/checkout@v4 
      
      - name: ls -la
        run: ls -la

      - name: Running a bash script
        uses: docker://node:18.20-alpine3.20
        with:
          entrypoint: ./example.sh
          args: "Danico 21"          
