name: Docker
on: [workflow_dispatch]
jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        FOO: bar
    steps:
      - name: Log Node & OS versions
        run: |
          node -v
          cat /etc/*-release
          echo "FOO=$FOO"