name: Testing dotCLI
on: 
  workflow_dispatch:

jobs:
  dotcli-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Context
        run: |
          uname -a

      - name: Checkout dotCLI
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Setup Expect
        run: sudo apt-get install -y expect

      - name: Install dotCLI
        run: npm install -g @dotcms/dotcli@rc

      - name: Check dotCLI version
        run: dotcli --version

      - name: Configure dotCLI
        run: |
          ./.github/scripts/config-automation.exp

      - name: dotCLI commands
        id: dotcli-commands
        continue-on-error: true          
        run: |
          dotcli login --user ${{ secrets.DOTCMS_USERNAME }} --password ${{ secrets.DOTCMS_PASSWORD }} -e

      - name: dotCLI pull demo
        if: always()
        run: |
          dotcli pull --token=${{ secrets.DOTCMS_TOKEN }} --dotcms-url=https://demo.dotcms.com     

      # - name: Run dotCLI commands
      #   run: |
      #     echo "::group::dotcli commands"
      #     dotcli config
      #     expect "Enter the key/name"
      #     # dotcli login --username ${{ secrets.DOTCMS_USERNAME }} --password ${{ secrets.DOTCMS_PASSWORD }}
      #     echo "::endgroup::"