name: Slack Notification
on: [workflow_dispatch]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send a slack message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.DOTCMS_SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#scout_equipo'
          SLACK_TITLE: "Important news!"
          SLACK_MESSAGE: "<!channel> This automated script is excited to announce the release of a new version of dotCLI (1.0.0-rc.1)!"
          SLACK_USERNAME: dotBot
          SLACK_MSG_AUTHOR: " "
          MSG_MINIMAL: true
          SLACK_FOOTER: ""          
          SLACK_ICON: https://avatars.slack-edge.com/temp/2021-12-08/2830145934625_e4e464d502865ff576e4.png
          # SLACK_COLOR: "#723fc4"
          # SLACK_ICON_EMOJI: ':rocket:'